//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVarsenoTask
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyProjectEntities : DbContext
    {
        public MyProjectEntities()
            : base("name=MyProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TODOLISTTABLE> TODOLISTTABLEs { get; set; }
        public virtual DbSet<TODOLISTTYPE> TODOLISTTYPEs { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }

        public System.Data.Entity.DbSet<MyVarsenoTask.Models.Login> Logins { get; set; }

        public System.Data.Entity.DbSet<MyVarsenoTask.Models.Registration> Registrations { get; set; }

        public System.Data.Entity.DbSet<MyVarsenoTask.Models.EditModel> EditModels { get; set; }
    }
}
