//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyVarsenoTask
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TODOLISTTABLE
    {
        public int ToDoListId { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
        [Required(ErrorMessage = "Please Enter The Title")]
        [Display(Name = "Title")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Please Enter The Task")]
        [Display(Name = "Task")]
        public string Task { get; set; }
        public Nullable<int> PriorityId { get; set; }
    
        public virtual TODOLISTTYPE TODOLISTTYPE { get; set; }
    }
}
